### ISSUE TITLE
Highest privacy shielding blocks sessionStorage and localStorage

### ISSUE THREAD

**Issue by Fryuni** [croct-tech/sdk-js#74]
## 🐞 Bug report
On privacy-first browsers, like Brave, the highest shielding option prevents use of the cross-site cookies and cross-site access to sessionStorage and localStorage.

```
Uncaught (in promise) DOMException: Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document.
    at Re.getGlobalTabStorage (https://cdn.croct.io/js/v1/lib/plug.js:1:46499)
    at Re.createContext (https://cdn.croct.io/js/v1/lib/plug.js:1:44579)
    at Re.getContext (https://cdn.croct.io/js/v1/lib/plug.js:1:44491)
    at Function.Ge.init (https://cdn.croct.io/js/v1/lib/plug.js:1:49823)
    at Function.sn.init (https://cdn.croct.io/js/v1/lib/plug.js:1:66212)
    at i.plug (https://cdn.croct.io/js/v1/lib/plug.js:1:69417)
    at https://cdn.test.croct.io/playground/master/index.js:55:32
```

Effectively, as intended, this prevents our SDK from working, but we should handle those exceptions and turn the SDK tracer in a NoOp.

### Steps to reproduce

1. Open the playground in Brave
2. Change the shield options to:
   * Cookies blocked
   * Cross-site fingerprinting blocked

### Expected behavior
No events should be tracked, but no error should surface. All tracking methods should do nothing and not throw any errors.

**Comment by marcospassos** [comment]
Related to #75

**Comment by marcospassos** [comment]
Thanks for reporting this! We're closing this issue as there is nothing we can do (at least easily) to fix this for CDN. As far as I understand, it should not affect applications using NPM.
